import React, { useState } from 'react';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import PromptCard from '../components/prompt/PromptCard';
import Modal from '../components/ui/Modal';
import PromptOutput from '../components/prompt/PromptOutput';
import Button from '../components/ui/Button';
import { Search, SlidersHorizontal, Sparkles } from 'lucide-react';

export function ExplorePage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedFramework, setSelectedFramework] = useState('All');
  const [selectedType, setSelectedType] = useState('All');
  const [selectedPrompt, setSelectedPrompt] = useState(null);

  const frameworks = ['All', 'React', 'Next.js', 'Vue', 'Python FastAPI', 'Node.js Express', 'Flutter'];
  const types = ['All', 'Code Prompt', 'Design Prompt', 'Database Prompt', 'API Prompt', 'Authentication Prompt'];

  // Mock public library items
  const publicPrompts = [
    {
      id: '1',
      title: 'Full-Stack SaaS Admin Panel',
      framework: 'React',
      prompt_type: 'Code Prompt',
      likes_count: 120,
      description: 'Includes user management tables, charts, dark mode configurations, JWT authentications, and PostgreSQL schema.',
      content: `# Project: SaaS Admin Dashboard\n\n## Tech Stack\n- Frontend: React\n- Styling: Tailwind CSS\n- Authentication: JWT Tokens\n\n## Database Models\n- Users table\n- Roles table\n- Activity logs\n\n## Folder Structure\n\`\`\`\n/src\n  /components\n  /pages\n  /services\n\`\`\``
    },
    {
      id: '2',
      title: 'E-commerce Store Front',
      framework: 'Next.js',
      prompt_type: 'Design Prompt',
      likes_count: 98,
      description: 'Features product filters, animated shopping carts, checkout layouts, and SEO schema tags.',
      content: `# Project: NextJS E-commerce Store\n\n## UI Mockup Details\n- Hero banner layouts\n- Products grid\n- Interactive shopping drawer\n\n## Color Palette\n- Primary: Indigo 600\n- Secondary: Cyan 400`
    },
    {
      id: '3',
      title: 'Real-time Chat App Channels',
      framework: 'Node.js Express',
      prompt_type: 'Database Prompt',
      likes_count: 85,
      description: 'Detailed WebSocket channel management, event models, offline message sync, and scalable room collections.',
      content: `# Project: Real-time Messaging\n\n## DB Schemas\n\`\`\`sql\nCREATE TABLE messages (\n  id UUID PRIMARY KEY,\n  room_id UUID REFERENCES rooms(id),\n  sender_id UUID REFERENCES users(id),\n  body TEXT,\n  created_at TIMESTAMP\n);\n\`\`\``
    },
    {
      id: '4',
      title: 'FastAPI OAuth Authentication Hub',
      framework: 'Python FastAPI',
      prompt_type: 'Authentication Prompt',
      likes_count: 54,
      description: 'Google, GitHub logins flow configuration, secure cookies handling, token refresh schemas, and rate limit definitions.',
      content: `# Project: FastAPI Security Suite\n\n## Authentication Configuration\n- Password hashing with bcrypt\n- JWT generation with PyJWT\n- OAuth2PasswordBearer flows`
    },
  ];

  const filteredPrompts = publicPrompts.filter((p) => {
    const matchesSearch = p.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          p.description.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesFramework = selectedFramework === 'All' || p.framework === selectedFramework;
    const matchesType = selectedType === 'All' || p.prompt_type === selectedType;
    return matchesSearch && matchesFramework && matchesType;
  });

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      
      <main className="flex-grow bg-dot-pattern py-12">
        <div className="max-w-7xl mx-auto px-6 flex flex-col gap-10">
          
          {/* Header Title */}
          <div className="flex flex-col gap-3 items-center text-center">
            <h1 className="text-3xl md:text-5xl font-black text-text-primary">
              Explore <span className="gradient-text">Gallery</span>
            </h1>
            <p className="text-sm text-text-secondary max-w-xl">
              Browse, copy, and download prompts generated by developers from the community. Apply quick filters to find your stack.
            </p>
          </div>

          {/* Filter Toolbar controls */}
          <div className="flex flex-col md:flex-row gap-4 items-center justify-between bg-bg-secondary p-4 rounded-2xl border border-border-color shadow-sm">
            {/* Search Input */}
            <div className="relative w-full md:max-w-sm flex items-center">
              <Search className="absolute left-4 text-text-tertiary w-4 h-4" />
              <input
                type="text"
                placeholder="Search templates..."
                className="w-full bg-surface-100 dark:bg-surface-900 border border-border-color rounded-xl pl-11 pr-4 py-2.5 text-sm text-text-primary focus:outline-none"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            </div>

            {/* Select filter menus */}
            <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
              {/* Framework */}
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold text-text-secondary">Framework:</span>
                <select
                  className="bg-surface-100 dark:bg-surface-900 border border-border-color rounded-xl px-3 py-2 text-xs text-text-primary focus:outline-none"
                  value={selectedFramework}
                  onChange={(e) => setSelectedFramework(e.target.value)}
                >
                  {frameworks.map(f => <option key={f} value={f}>{f}</option>)}
                </select>
              </div>

              {/* Prompt Type */}
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold text-text-secondary">Type:</span>
                <select
                  className="bg-surface-100 dark:bg-surface-900 border border-border-color rounded-xl px-3 py-2 text-xs text-text-primary focus:outline-none"
                  value={selectedType}
                  onChange={(e) => setSelectedType(e.target.value)}
                >
                  {types.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
            </div>
          </div>

          {/* Prompt card grid list */}
          {filteredPrompts.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredPrompts.map((prompt) => (
                <PromptCard
                  key={prompt.id}
                  prompt={prompt}
                  onSelect={(p) => setSelectedPrompt(p)}
                />
              ))}
            </div>
          ) : (
            <div className="flex flex-col items-center gap-3 py-20 text-center">
              <Sparkles className="w-10 h-10 text-text-tertiary" />
              <span className="font-bold text-text-primary text-lg">No Blueprints Found</span>
              <p className="text-text-secondary text-xs max-w-xs">
                Try adjustment filters or search parameter values to view templates.
              </p>
            </div>
          )}

        </div>
      </main>

      {/* Details overlay Modal */}
      <Modal
        isOpen={!!selectedPrompt}
        onClose={() => setSelectedPrompt(null)}
        title={selectedPrompt?.title || 'Blueprint Details'}
        size="xl"
      >
        {selectedPrompt && <PromptOutput prompt={selectedPrompt} />}
      </Modal>

      <Footer />
    </div>
  );
}

export default ExplorePage;
